{"uuid":"cc237fcc-87f2-4902-97b7-72800de556de","historyId":"ddd2d4b732ae4fd8a66dcf3ee2e7a348","fullName":"com.qnsz.windowsuiauto.testcase.invite.InviteFrequentlyUsedContactsTest.test3CreateRoom","labels":[{"name":"package","value":"com.qnsz.windowsuiauto.testcase.invite.InviteFrequentlyUsedContactsTest"},{"name":"testClass","value":"com.qnsz.windowsuiauto.testcase.invite.InviteFrequentlyUsedContactsTest"},{"name":"testMethod","value":"test3CreateRoom"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"WindowsUIAuto1"},{"name":"subSuite","value":"com.qnsz.windowsuiauto.testcase.invite.InviteFrequentlyUsedContactsTest"},{"name":"host","value":"lixijun"},{"name":"thread","value":"38044@lixijun.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"主持人创建会议","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'LIXIJUN', ip: '172.25.11.194', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: AppiumDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\n    at errorFromW3CJsonCode (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:780:25)\n    at ProxyRequestError.getActualError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:663:14)\n    at WADProxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:272:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at condFn (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:182:9)\n    at spin (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:138:20)\n    at waitForCondition (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:155:10)\n    at WinAppDriver._startSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:192:7)\n    at WinAppDriver.start (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:167:5)\n    at WindowsDriver.startWinAppDriverSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:79:5)\n    at WindowsDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:67:7)\n    at AppiumDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\lib\\appium.js:387:35)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'LIXIJUN', ip: '172.25.11.194', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: AppiumDriver","trace":"org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'LIXIJUN', ip: '172.25.11.194', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: AppiumDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\n    at errorFromW3CJsonCode (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:780:25)\n    at ProxyRequestError.getActualError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:663:14)\n    at WADProxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:272:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at condFn (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:182:9)\n    at spin (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:138:20)\n    at waitForCondition (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:155:10)\n    at WinAppDriver._startSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:192:7)\n    at WinAppDriver.start (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:167:5)\n    at WindowsDriver.startWinAppDriverSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:79:5)\n    at WindowsDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:67:7)\n    at AppiumDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\lib\\appium.js:387:35)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'LIXIJUN', ip: '172.25.11.194', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: AppiumDriver\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)\r\n\tat io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)\r\n\tat io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)\r\n\tat com.qnsz.windowsuiauto.utils.General.getComputerTwo(General.java:74)\r\n\tat com.qnsz.windowsuiauto.testcase.login.Test1Base.init(Test1Base.java:25)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)\r\n\tat org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:529)\r\n\tat org.testng.TestRunner.run(TestRunner.java:497)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)\r\n\t... 36 more\r\nCaused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'LIXIJUN', ip: '172.25.11.194', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: AppiumDriver\nremote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 操作超时。 (异常来自 HRESULT:0x80131505)\n    at errorFromW3CJsonCode (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:780:25)\n    at ProxyRequestError.getActualError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:663:14)\n    at WADProxy.command (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\jsonwp-proxy\\proxy.js:272:19)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at condFn (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:182:9)\n    at spin (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:138:20)\n    at waitForCondition (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\asyncbox\\lib\\asyncbox.js:155:10)\n    at WinAppDriver._startSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:192:7)\n    at WinAppDriver.start (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\winappdriver.js:167:5)\n    at WindowsDriver.startWinAppDriverSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:79:5)\n    at WindowsDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-windows-driver\\lib\\driver.js:67:7)\n    at AppiumDriver.createSession (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\lib\\appium.js:387:35)\r\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\r\n\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\r\n\tat org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)\r\n\tat org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)\r\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)\r\n\tat java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)\r\n\tat java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)\r\n\tat java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)\r\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)\r\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)\r\n\tat java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)\r\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r\n\tat java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)\r\n\tat org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)\r\n\t... 41 more\r\n"},"stage":"finished","description":"测试机1创建会议","steps":[],"attachments":[],"parameters":[],"start":1691645851382,"stop":1691645851383}